name: miko
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: love fashion // think green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#2f4e4d'
    - '#c0a69c'
    - '#a7373f'
    - '#8d7466'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
