name: made by miko
favicon: null
layout_spectrum: 0.24415
typography_spectrum: 0.86476
title: love fashion // think green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#2e2d35'
    - '#6d6f7b'
    - '#e76c6e'
    - '#dba589'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
