name: made by miko
favicon: null
layout_spectrum: 0.07707
typography_spectrum: 0.86476
title: love fashion // think green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#315964'
    - '#1e1f24'
    - '#548a96'
    - '#c79c85'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
