name: miko
favicon: null
layout_spectrum: 0.77908
typography_spectrum: 0.88055
title: love fashion // think green
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#2f4e4d'
    - '#c0a69c'
    - '#a7373f'
    - '#8d7466'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
