name: miko
favicon: null
layout_spectrum: 0.5029946018476039
typography_spectrum: 0.3663756081368774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#2f4e4d'
    - '#c0a69c'
    - '#a7373f'
    - '#8d7466'
  brandStrength: 0.7009464364964515
  lightness: 0.4334709735121578
  saturation: 0.7446167815942317
  rhythmicContrast: 0.4460436606314033
purpose: []
